# Generated by Django 4.2.7 on 2023-11-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_accountmodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
